objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Outdoor Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fitness Centre</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Spa</fullName>
            </value>
            <value>
                <fullName>Billiards Table</fullName>
            </value>
            <value>
                <fullName>Package Lockers</fullName>
            </value>
            <value>
                <fullName>Playgrounds</fullName>
            </value>
            <value>
                <fullName>Walking Paths</fullName>
            </value>
            <value>
                <fullName>Pet-friendly spaces</fullName>
            </value>
            <value>
                <fullName>Parks</fullName>
            </value>
            <value>
                <fullName>Valet Trash</fullName>
            </value>
            <value>
                <fullName>Surveillance cameras</fullName>
            </value>
            <value>
                <fullName>Green Surrounding Neighborhood</fullName>
            </value>
            <value>
                <fullName>Building Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Clubhouse</fullName>
            </value>
            <value>
                <fullName>Party room</fullName>
            </value>
            <value>
                <fullName>Social area or Rooftop garden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Property__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <type>Address</type>
</CustomField>

objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Flats</fullName>
            </value>
            <value>
                <fullName>Individual House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Bungalows</fullName>
            </value>
            <value>
                <fullName>Farmhouse</fullName>
            </value>
            <value>
                <fullName>Beach houses</fullName>
            </value>
            <value>
                <fullName>Mobile homes</fullName>
            </value>
            <value>
                <fullName>Row Houses</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Office buildings</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Warehouses</fullName>
            </value>
            <value>
                <fullName>Factories</fullName>
            </value>
            <value>
                <fullName>Regional mall</fullName>
            </value>
            <value>
                <fullName>Strip center</fullName>
            </value>
            <value>
                <fullName>Outlet centers</fullName>
            </value>
            <value>
                <fullName>Power Center</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Ready to Move</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Basketball court</fullName>
            </value>
            <value>
                <fullName>Washer and Dryer in-unit</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>High-end Finishes and Fixtures</fullName>
            </value>
            <value>
                <fullName>Central air conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Balcony</fullName>
            </value>
            <value>
                <fullName>Smart home</fullName>
            </value>
            <value>
                <fullName>Security systems and intercom</fullName>
            </value>
            <value>
                <fullName>Large bathtubs</fullName>
            </value>
            <value>
                <fullName>Complimentary Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Online Rent Options</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Balcony_Count__c.field-meta.xml
<CustomField>
    <fullName>Balcony_Count__c</fullName>
    <label>Balcony Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Bathrooms__c</fullName>
    <label>Bathrooms</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Carpet Area (sqft)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Display_Preference__c.field-meta.xml
<CustomField>
    <fullName>Display_Preference__c</fullName>
    <label>Display Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corner Units</fullName>
            </value>
            <value>
                <fullName>High Foot Traffic Areas</fullName>
            </value>
            <value>
                <fullName>Shopping Malls (Near Anchors or Entrances)</fullName>
            </value>
            <value>
                <fullName>Tourist Areas</fullName>
            </value>
            <value>
                <fullName>Residential Neighborhood Corners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Floor_Number__c</fullName>
    <label>Floor Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Unit__c/fields/Full_Unit_Label__c.field-meta.xml
<CustomField>
    <fullName>Full_Unit_Label__c</fullName>
    <formula>Property__r.Name +&apos;-&apos;+ Tower__r.Name + &apos;-&apos; + Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Unit Label</label>
    <type>Text</type>
</CustomField>

objects/Unit__c/fields/Furnishings__c.field-meta.xml
<CustomField>
    <fullName>Furnishings__c</fullName>
    <label>Furnishings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Furnished</fullName>
            </value>
            <value>
                <fullName>Semi Furnished</fullName>
            </value>
            <value>
                <fullName>Unfurnished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <type>Date</type>
</CustomField>

objects/Unit__c/fields/No_Of_Parking_Area__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Parking_Area__c</fullName>
    <label>No.Of.Parking Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit__c/fields/Rental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rental_Amount__c</fullName>
    <label>Rental Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Unit__c/fields/Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>Square_Footage__c</fullName>
    <label>Square Footage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Total_Selling_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Amount__c</fullName>
    <label>Total Selling Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Deluxe Room</fullName>
            </value>
            <value>
                <fullName>Executive Suite</fullName>
            </value>
            <value>
                <fullName>Individual House</fullName>
            </value>
            <value>
                <fullName>Industrial Unit</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Office Space</fullName>
            </value>
            <value>
                <fullName>Office Suite</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Presidential Suite</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Standard Room</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/GetResidentialPropertyDetails.cls
public class GetResidentialPropertyDetails {
     public static List<PropertyAndUnitResponseWrapper> residentialPropertyDetails(PropertyAndUnitRequestWrapper getDetails,Id residentialRecordTypeId, Id mixedUseRecordTypeId){
        String propertyQuery;
        String unitQuery;
        List<Id> propertyIdList=new List<Id>();
        propertyQuery='SELECT Id FROM Property__c WHERE (RecordTypeId=:residentialRecordTypeId OR RecordTypeId=:mixedUseRecordTypeId)';
         /*if(!String.isBlank(getDetails.propertyType)){
             propertyQuery+='AND Property_Type__c=:getDetails.propertyType';
         }*/
         if(!String.isBlank(getDetails.propertyStatus)){
             propertyQuery+='AND Status__c=\''+getDetails.propertyStatus+ '\'';
         }
         List<Property__c> propertyList=Database.Query(propertyQuery);
         for(Property__c propertyRecords:propertyList){
            propertyIdList.add(propertyRecords.Id);
        }
        unitQuery='SELECT Id,Amenities__c,Property__c,Property__r.name,Property__r.Property_Address__c,Square_Footage__c,Asset_Class__c,Balcony_Count__c,Bathrooms__c,Bedrooms__c,Carpet_Area__c,Floor_Number__c,Furnishings__c,Handover__c,Name,Full_Unit_Label__c,Available_Booked_Sold_Rented__c,Rental_Amount__c,Total_Selling_Amount__c,Unit_Type__c,No_of_Parking_Area__c,Display_Preference__c FROM Unit__c WHERE Property__c IN:propertyIdList AND Available_Booked_Sold_Rented__c=\'Available\'';
          if(!String.isBlank(getDetails.unitType)){
         unitQuery+=' AND Unit_Type__c=\''+getDetails.unitType+'\'';
        }
         if(!String.isBlank(getDetails.furnishing)){
         unitQuery+=' AND Furnishings__c=\''+getDetails.furnishing+'\'';
        }
       if(getDetails.numberofBedrooms !=null && getDetails.numberofBedrooms !=0){
         unitQuery+=' AND Bedrooms__c='+getDetails.numberofBedrooms;
        }
       if(getDetails.numberofBathrooms !=null && getDetails.numberofBathrooms !=0){
         unitQuery+=' AND Bathrooms__c='+getDetails.numberofBathrooms;
        }
           if(getDetails.numberofParkingArea !=null || getDetails.numberofParkingArea !=0){
         unitQuery+=' AND No_of_Parking_Area__c='+getDetails.numberofParkingArea;
        }
          
       if(!String.isBlank(getDetails.rentOrBuy)){
           if(getDetails.rentOrBuy=='rent' && getDetails.budget!=null && getDetails.budget!=0){
                 unitQuery+=' AND Rental_Amount__c>='+getDetails.budget;
           }
           if(getDetails.rentOrBuy=='buy' && getDetails.budget!=null && getDetails.budget!=0){
              unitQuery+=' AND Total_Selling_Amount__c>='+getDetails.budget;
           }
        }
         
          List<Unit__c> unitList=Database.Query(unitQuery);
         List<PropertyAndUnitResponseWrapper> residentialResponse=constructResidentialResponse(unitList,getDetails.rentOrBuy);
         return residentialResponse;
    }
    public static  List<PropertyAndUnitResponseWrapper> constructResidentialResponse(List<Unit__c> unitList,String rentOrBuy){
          List<PropertyAndUnitResponseWrapper> propertyAndUnitResponseWrapperList=new  List<PropertyAndUnitResponseWrapper>();
		 for(Unit__c unitRecords:unitList){
            PropertyAndUnitResponseWrapper propertyAndUnitData=new PropertyAndUnitResponseWrapper();
            propertyAndUnitData.UnitName=unitRecords.Full_Unit_Label__c;
            propertyAndUnitData.area=String.valueOf(unitRecords.Square_Footage__c);
            propertyAndUnitData.address=String.valueOf(unitRecords.Property__r.Property_Address__c);
             propertyAndUnitData.unitHighlights=unitRecords.Amenities__c+' '+unitRecords.No_of_Parking_Area__c+' '+unitRecords.Handover__c;
            if(rentOrBuy=='rent'){
            propertyAndUnitData.pricing=String.valueOf(unitRecords.Rental_Amount__c);
                }
            if(rentOrBuy=='buy'){
                propertyAndUnitData.pricing=String.valueOf(unitRecords.Total_Selling_Amount__c);
            }
             propertyAndUnitResponseWrapperList.add(propertyAndUnitData);
        }
        return propertyAndUnitResponseWrapperList;
    }
    
  
}