objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Outdoor Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fitness Centre</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Spa</fullName>
            </value>
            <value>
                <fullName>Billiards Table</fullName>
            </value>
            <value>
                <fullName>Package Lockers</fullName>
            </value>
            <value>
                <fullName>Playgrounds</fullName>
            </value>
            <value>
                <fullName>Walking Paths</fullName>
            </value>
            <value>
                <fullName>Pet-friendly spaces</fullName>
            </value>
            <value>
                <fullName>Parks</fullName>
            </value>
            <value>
                <fullName>Valet Trash</fullName>
            </value>
            <value>
                <fullName>Surveillance cameras</fullName>
            </value>
            <value>
                <fullName>Green Surrounding Neighborhood</fullName>
            </value>
            <value>
                <fullName>Building Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Clubhouse</fullName>
            </value>
            <value>
                <fullName>Party room</fullName>
            </value>
            <value>
                <fullName>Social area or Rooftop garden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Property__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <type>Address</type>
</CustomField>

objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit__c/fields/Additional_Storage_Space__c.field-meta.xml
<CustomField>
    <fullName>Additional_Storage_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Storage Space</label>
    <type>Checkbox</type>
</CustomField>

objects/Unit__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Basketball court</fullName>
            </value>
            <value>
                <fullName>Washer and Dryer in-unit</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>High-end Finishes and Fixtures</fullName>
            </value>
            <value>
                <fullName>Central air conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Balcony</fullName>
            </value>
            <value>
                <fullName>Smart home</fullName>
            </value>
            <value>
                <fullName>Security systems and intercom</fullName>
            </value>
            <value>
                <fullName>Large bathtubs</fullName>
            </value>
            <value>
                <fullName>Complimentary Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Online Rent Options</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Balcony_Count__c.field-meta.xml
<CustomField>
    <fullName>Balcony_Count__c</fullName>
    <label>Balcony Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Bathrooms__c</fullName>
    <label>Bathrooms</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Carpet Area (sqft)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Display_Preference__c.field-meta.xml
<CustomField>
    <fullName>Display_Preference__c</fullName>
    <label>Display Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corner Units</fullName>
            </value>
            <value>
                <fullName>High Foot Traffic Areas</fullName>
            </value>
            <value>
                <fullName>Shopping Malls (Near Anchors or Entrances)</fullName>
            </value>
            <value>
                <fullName>Tourist Areas</fullName>
            </value>
            <value>
                <fullName>Residential Neighborhood Corners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Floor_Number__c</fullName>
    <label>Floor Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Unit__c/fields/Full_Unit_Label__c.field-meta.xml
<CustomField>
    <fullName>Full_Unit_Label__c</fullName>
    <formula>Property__r.Name +&apos;-&apos;+ Tower__r.Name + &apos;-&apos; + Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Unit Label</label>
    <type>Text</type>
</CustomField>

objects/Unit__c/fields/Furnishings__c.field-meta.xml
<CustomField>
    <fullName>Furnishings__c</fullName>
    <label>Furnishings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Furnished</fullName>
            </value>
            <value>
                <fullName>Semi Furnished</fullName>
            </value>
            <value>
                <fullName>Unfurnished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <type>Date</type>
</CustomField>

objects/Unit__c/fields/No_Of_Parking_Area__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Parking_Area__c</fullName>
    <label>No.Of.Parking Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Number_of_Seating_space__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Seating_space__c</fullName>
    <label>Number of Seating space</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit__c/fields/Rental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rental_Amount__c</fullName>
    <label>Rental Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Unit__c/fields/Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>Square_Footage__c</fullName>
    <label>Square Footage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Total_Selling_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Amount__c</fullName>
    <label>Total Selling Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Deluxe Room</fullName>
            </value>
            <value>
                <fullName>Executive Suite</fullName>
            </value>
            <value>
                <fullName>Individual House</fullName>
            </value>
            <value>
                <fullName>Industrial Unit</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Office Space</fullName>
            </value>
            <value>
                <fullName>Office Suite</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Presidential Suite</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Standard Room</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/GetCommercialPropertyDetails.cls
public class GetCommercialPropertyDetails {
    public static List<PropertyAndUnitResponseWrapper> commercialPropertyDetails(PropertyAndUnitRequestWrapper getDetails,Id commercialRecordTypeId,Id mixedUseRecordTypeId){
       String propertyQuery;
        String unitQuery;
        List<Id> propertyIdList=new List<Id>();
        propertyQuery='SELECT Id FROM Property__c WHERE (RecordTypeId=:commercialRecordTypeId OR RecordTypeId=:mixedUseRecordTypeId)';
  		 List<Property__c> propertyList=Database.Query(propertyQuery);
         for(Property__c propertyRecords:propertyList){
            propertyIdList.add(propertyRecords.Id);
            
        }
          system.debug(propertyIdList);
       unitQuery='SELECT Id,Amenities__c,Property__c,Property__r.name,Property__r.Property_Address__c,Square_Footage__c,Asset_Class__c,Balcony_Count__c,Bathrooms__c,Bedrooms__c,Carpet_Area__c,Floor_Number__c,Furnishings__c,Handover__c,Name,Full_Unit_Label__c,Available_Booked_Sold_Rented__c,Rental_Amount__c,Total_Selling_Amount__c,Display_Preference__c,Number_of_Seating_space__c,Additional_Storage_Space__c,No_of_Parking_Area__c FROM Unit__c WHERE Property__c IN:propertyIdList AND Available_Booked_Sold_Rented__c=\'Available\'';
         if(!String.isBlank(getDetails.unitType)){
         unitQuery+=' AND Unit_Type__c=\''+getDetails.unitType+'\'';
        }
         if(!String.isBlank(getDetails.furnishing)){
         unitQuery+=' AND Furnishings__c=\''+getDetails.furnishing+'\'';
        }
        if(!String.isBlank(getDetails.rentOrBuy)){
           if(getDetails.rentOrBuy=='rent' && getDetails.budget!=null && getDetails.budget!=0){
                 unitQuery+=' AND Rental_Amount__c>='+getDetails.budget;
           }
           if(getDetails.rentOrBuy=='buy' && getDetails.budget!=null && getDetails.budget!=0){
               unitQuery+=' AND Total_Selling_Amount__c>='+getDetails.budget;
           }
        }
         if( getDetails.noOfSeatingSpace!=null && getDetails.noOfSeatingSpace!=0){
                 unitQuery+=' AND Number_of_Seating_space__c>='+String.valueOf(getDetails.noOfSeatingSpace);
         }
          if(getDetails.squareFootage !=null && getDetails.squareFootage !=0){
           unitQuery+=' AND Square_Footage__c >='+String.valueOf(getDetails.squareFootage);
        }
          if(getDetails.numberofParkingArea !=null && getDetails.numberofParkingArea !=0){
           unitQuery+=' AND No_of_Parking_Area__c >='+String.valueOf(getDetails.numberofParkingArea);
        }
           if(!String.isBlank(getDetails.additionalStorageSpace)){
           unitQuery+=' AND Additional_Storage_Space__c='+getDetails.additionalStorageSpace;
        }
         
          List<Unit__c> unitList=Database.Query(unitQuery);
         List<PropertyAndUnitResponseWrapper> retailResponse=constructRetailResponse(unitList,getDetails.rentOrBuy);
         return retailResponse;
    }
    public static  List<PropertyAndUnitResponseWrapper> constructRetailResponse(List<Unit__c> unitList,String rentOrBuy){
          List<PropertyAndUnitResponseWrapper> propertyAndUnitResponseWrapperList=new  List<PropertyAndUnitResponseWrapper>();
		 for(Unit__c unitRecords:unitList){
            PropertyAndUnitResponseWrapper propertyAndUnitData=new PropertyAndUnitResponseWrapper();
            propertyAndUnitData.UnitName=unitRecords.Full_Unit_Label__c;
            propertyAndUnitData.area=String.valueOf(unitRecords.Square_Footage__c);
            propertyAndUnitData.address=String.valueOf(unitRecords.Property__r.Property_Address__c);
             if(rentOrBuy=='rent'){
            propertyAndUnitData.pricing=String.valueOf(unitRecords.Rental_Amount__c);
                }
            if(rentOrBuy=='buy'){
                propertyAndUnitData.pricing=String.valueOf(unitRecords.Total_Selling_Amount__c);
            }
             propertyAndUnitResponseWrapperList.add(propertyAndUnitData);
        }
        return propertyAndUnitResponseWrapperList;
    }  

}