objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Outdoor Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fitness Centre</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Spa</fullName>
            </value>
            <value>
                <fullName>Billiards Table</fullName>
            </value>
            <value>
                <fullName>Package Lockers</fullName>
            </value>
            <value>
                <fullName>Playgrounds</fullName>
            </value>
            <value>
                <fullName>Walking Paths</fullName>
            </value>
            <value>
                <fullName>Pet-friendly spaces</fullName>
            </value>
            <value>
                <fullName>Parks</fullName>
            </value>
            <value>
                <fullName>Valet Trash</fullName>
            </value>
            <value>
                <fullName>Surveillance cameras</fullName>
            </value>
            <value>
                <fullName>Green Surrounding Neighborhood</fullName>
            </value>
            <value>
                <fullName>Building Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Clubhouse</fullName>
            </value>
            <value>
                <fullName>Party room</fullName>
            </value>
            <value>
                <fullName>Social area or Rooftop garden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Ready to Move</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Property__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <description>Commercial</description>
    <label>Commercial</label>
</RecordType>

objects/Property__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <description>Residential Apartment</description>
    <label>Residential</label>
</RecordType>

objects/Property__c/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <description>Retail</description>
    <label>Retail</label>
</RecordType>

objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Basketball court</fullName>
            </value>
            <value>
                <fullName>Washer and Dryer in-unit</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>High-end Finishes and Fixtures</fullName>
            </value>
            <value>
                <fullName>Central air conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Balcony</fullName>
            </value>
            <value>
                <fullName>Smart home</fullName>
            </value>
            <value>
                <fullName>Security systems and intercom</fullName>
            </value>
            <value>
                <fullName>Large bathtubs</fullName>
            </value>
            <value>
                <fullName>Complimentary Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Online Rent Options</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Balcony_Count__c.field-meta.xml
<CustomField>
    <fullName>Balcony_Count__c</fullName>
    <label>Balcony Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Bathrooms__c</fullName>
    <label>Bathrooms</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Carpet Area (sqft)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Unit__c/fields/Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Floor_Number__c</fullName>
    <label>Floor Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Unit__c/fields/Furnishings__c.field-meta.xml
<CustomField>
    <fullName>Furnishings__c</fullName>
    <label>Furnishings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Furnished</fullName>
            </value>
            <value>
                <fullName>Semi Furnished</fullName>
            </value>
            <value>
                <fullName>Unfurnished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <type>Date</type>
</CustomField>

objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Unit__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <description>Commercial Unit</description>
    <label>Commercial</label>
</RecordType>

objects/Unit__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <description>Residential Unit</description>
    <label>Residential</label>
</RecordType>

objects/Unit__c/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <description>Retail unit</description>
    <label>Retail</label>
</RecordType>

classes/GetPropertyAndUnitDetails.cls
public class GetPropertyAndUnitDetails {
    @InvocableMethod
    public static List<String> generatePromptTemplateResponse(List<String> propertyAndUnitDetails) {
        PropertyAndUnitRequestWrapper convertedPropertyAndUnitDetails;
          List<String> jsonResponse=new List<String>();
         system.debug(propertyAndUnitDetails);
        //call the prompt template using connect API
        ConnectApi.WrappedValue inputValue = new ConnectApi.WrappedValue();
        inputValue.value = propertyAndUnitDetails[0];
        Map<String, ConnectApi.WrappedValue> inputParams = new Map<String, ConnectApi.WrappedValue>();
        inputParams.put('Input:Property_and_unit_details', inputValue);
        ConnectApi.EinsteinPromptTemplateGenerationsInput executeTemplateInput = new ConnectApi.EinsteinPromptTemplateGenerationsInput();
        executeTemplateInput.additionalConfig = new ConnectApi.EinsteinLlmAdditionalConfigInput();
        executeTemplateInput.additionalConfig.applicationName = 'PromptBuilderPreview';
        executeTemplateInput.isPreview = false;
        executeTemplateInput.inputParams = inputParams;
        
        try {
            // Call the service
            ConnectApi.EinsteinPromptTemplateGenerationsRepresentation generationsOutput = ConnectApi.EinsteinLLM.generateMessagesForPromptTemplate(
                'Get_Property_and_unit_details',
                executeTemplateInput
            );
            if (!generationsOutput.generations.isEmpty()) {
                String jsonValue;
                ConnectApi.EinsteinLLMGenerationItemOutput response = generationsOutput.generations[0];
                System.debug('Response : ' + response.text);
                jsonValue=response.text.substringAfter('{');
                jsonValue='{'+jsonValue;
                system.debug(jsonValue);
                convertedPropertyAndUnitDetails=(PropertyAndUnitRequestWrapper)JSON.deserialize(jsonValue, PropertyAndUnitRequestWrapper.class);
                System.debug('propertyAndUnitDetailsJSON : ' + convertedPropertyAndUnitDetails);
                //Query the matching property and unit
                List<PropertyAndUnitResponseWrapper> getResponse=getPropertyAndUnitDetails(convertedPropertyAndUnitDetails);
				jsonResponse.add(JSON.serialize(getResponse));
            } 
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw e;
        }
        return jsonResponse;
    }
    //Get the matching property and unit and add it in the response wrapper
   /* public static   List<PropertyAndUnitResponseWrapper> getPropertyAndUnitDetails(PropertyAndUnitRequestWrapper getDetails){
        List<Id> propertyIdList=new List<Id>();
        List<PropertyAndUnitResponseWrapper> propertyAndUnitResponseWrapperList=new  List<PropertyAndUnitResponseWrapper>();
        //Declare property record type
        Id residentialRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Residential').getRecordTypeId();
        Id retailRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Retail').getRecordTypeId();
        Id commercialRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Commercial').getRecordTypeId();
         Id mixedUseRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Mixed Use').getRecordTypeId();
        List<Property__c> propertyList=[SELECT Id FROM Property__c WHERE Status__c=:getDetails.propertyStatus];
        for(Property__c propertyRecords:propertyList){
            propertyIdList.add(propertyRecords.Id);
        }
        List<Unit__c> unitList=[SELECT Id,Amenities__c,Property__c,Property__r.name,Area__c,Asset_Class__c,Balcony_Count__c,Bathrooms__c,Bedrooms__c,Carpet_Area__c,Floor_Number__c,Furnishings__c,Handover__c,Name FROM Unit__c WHERE Furnishings__c=:getDetails.furnishing AND Property__c IN:propertyIdList ];
        for(Unit__c unitRecords:unitList){
            PropertyAndUnitResponseWrapper propertyAndUnitData=new PropertyAndUnitResponseWrapper();
            propertyAndUnitData.unitName=unitRecords.Name;
            propertyAndUnitResponseWrapperList.add(propertyAndUnitData);
        }
        return propertyAndUnitResponseWrapperList;
    }*/
   
 public static   List<PropertyAndUnitResponseWrapper> getPropertyAndUnitDetails(PropertyAndUnitRequestWrapper getDetails){
        List<Id> propertyIdList=new List<Id>();
        List<PropertyAndUnitResponseWrapper> propertyAndUnitResponseWrapperList=new  List<PropertyAndUnitResponseWrapper>();
        //Declare property record type
        Id residentialRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Residential').getRecordTypeId();
        Id retailRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Retail').getRecordTypeId();
        Id commercialRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Commercial').getRecordTypeId();
         Id mixedUseRecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Mixed Use').getRecordTypeId();
     if(getDetails.assetType=='Residential'){
         propertyAndUnitResponseWrapperList=GetResidentialPropertyDetails.residentialPropertyDetails(getDetails,residentialRecordTypeId,mixedUseRecordTypeId);
     }
     if(getDetails.assetType=='Retail'){
         propertyAndUnitResponseWrapperList=GetRetailPropertyDetails.retailPropertyDetails(getDetails,retailRecordTypeId,mixedUseRecordTypeId);
     }
       if(getDetails.assetType=='commercial'){
         propertyAndUnitResponseWrapperList=GetCommercialPropertyDetails.commercialPropertyDetails(getDetails,commercialRecordTypeId,mixedUseRecordTypeId);
     }
        return propertyAndUnitResponseWrapperList;
    }
}